basePath: /
definitions:
  userdto.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  userdto.LoginResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/userdto.UserPrivateDTO'
    type: object
  userdto.UserPrivateDTO:
    properties:
      avatar:
        type: string
      email:
        type: string
      id:
        type: integer
      phone:
        type: string
      username:
        type: string
    type: object
  userdto.UserPublicDTO:
    properties:
      avatar:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
  userdto.UserUpdateRequest:
    properties:
      avatar:
        type: string
      username:
        type: string
    type: object
  v1.PageResponse:
    properties:
      data: {}
      page:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: 接口文档
  title: go-server API
  version: "1.0"
paths:
  /user/{id}:
    delete:
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: string
      summary: 删除用户
      tags:
      - 用户
  /user/info:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userdto.UserPrivateDTO'
      summary: 获取当前用户信息
      tags:
      - 用户
    put:
      consumes:
      - application/json
      parameters:
      - description: 更新参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/userdto.UserUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userdto.UserPrivateDTO'
      summary: 更新当前用户
      tags:
      - 用户
  /user/login:
    post:
      consumes:
      - application/json
      description: 输入账号密码获取 token
      parameters:
      - description: 登录参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/userdto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userdto.LoginResponse'
      summary: 用户登录
      tags:
      - 用户
  /user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 注册参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/userdto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userdto.UserPrivateDTO'
      summary: 用户注册
      tags:
      - 用户
  /users:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/userdto.UserPublicDTO'
            type: array
      summary: 用户列表
      tags:
      - 用户
  /users/{id}:
    get:
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userdto.UserPublicDTO'
      summary: 获取用户详情
      tags:
      - 用户
  /users/list:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.PageResponse'
      summary: 用户列表 分页
      tags:
      - 用户
swagger: "2.0"
